name: Deploy to Host in Hostinger

on: [push]

jobs:
  trigger-build:
    name: Trigger Clone and Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: Panteraroze@2000?
#          key: ${{ secrets.VM_SSH_KEY }}
      - run: ./root/setup.sh